sudo: required
services:
  - docker

before_install:
  - gem install bundler --pre
  - docker build -t aleksandargujas/dockertoy -f Dockerfile.dev .

script:
  - docker run -e CI=true aleksandargujas/dockertoy npm run test