sudo: required
services:
  - docker

before_install:
  - docker build -t aleksandargujas/dockertoy -f Dockerfile.dev .

script:
  - docker run aleksandargujas/dockertoy npm run test -- --coverage







  # script:
  # - docker run -e CI=true USERNAME/docker-react npm run test


# language: generic 