sudo: required
services:
  - docker

before_install:
  - docker build -t aleksandargujas/dockertoy -f Dockerfile.dev .

script:
  - docker run -e CI=true aleksandargujas/dockertoy npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerToy"
  env: "Dockertoy-env"
  bucket_name: "elasticbeanstalk-us-east-2-684465203491"
  bucket_path: "DockerToy"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"
  